### ISSUE TITLE
systemd unit fails at start up but can be started manually after(Ubuntu 15.10).

### ISSUE THREAD

**Issue by JasonLG1979** [google/cloud-print-connector#140]
I followed the systemd instruction in the wiki on Ubuntu 15.10 server(mostly: corrected cups-connector.config.json to gcp-cups-connector.config.json).

This is what I get out of `systemctl status gcp` after a reboot:

```
● gcp.service - Google Cloud Print CUPS Connector
   Loaded: loaded (/etc/systemd/system/gcp.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2015-11-16 11:05:03 CST; 36s ago
  Process: 602 ExecStart=/opt/gcp_cups_connector/gcp-cups-connector -config-filename /etc/gcp_cups_connector/gcp-cups-connector.config.json (code=exited, status=255)
 Main PID: 602 (code=exited, status=255)

Nov 16 11:05:02 gray-server gcp-cups-connector[602]: /home/user/go/src/github.com/golang/glog/glog.go:646 +0x1b8
Nov 16 11:05:02 gray-server gcp-cups-connector[602]: github.com/golang/glog.(*loggingT).print(0xcfdbe0, 0xc800000003, 0xc8200bfe30, 0x1, 0x1)
Nov 16 11:05:02 gray-server gcp-cups-connector[602]: /home/user/go/src/github.com/golang/glog/glog.go:637 +0x50
Nov 16 11:05:02 gray-server gcp-cups-connector[602]: github.com/golang/glog.Fatal(0xc8200bfe30, 0x1, 0x1)
Nov 16 11:05:02 gray-server gcp-cups-connector[602]: /home/user/go/src/github.com/golang/glog/glog.go:1128 +0x49
Nov 16 11:05:02 gray-server gcp-cups-connector[602]: main.main()
Nov 16 11:05:02 gray-server gcp-cups-connector[602]: /home/user/go/src/github.com/google/cups-connector/gcp-cups-connector/gcp-cups-connector.go:89 +0xe80
Nov 16 11:05:03 gray-server systemd[1]: gcp.service: Main process exited, code=exited, status=255/n/a
Nov 16 11:05:03 gray-server systemd[1]: gcp.service: Unit entered failed state.
Nov 16 11:05:03 gray-server systemd[1]: gcp.service: Failed with result 'exit-code'.
```

After `systemctl start gcp` and `systemctl status gcp`  without rebooting all is well:

```
● gcp.service - Google Cloud Print CUPS Connector
   Loaded: loaded (/etc/systemd/system/gcp.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2015-11-16 11:06:16 CST; 10s ago
 Main PID: 1549 (gcp-cups-connec)
   CGroup: /system.slice/gcp.service
           └─1549 /opt/gcp_cups_connector/gcp-cups-connector -config-filename /etc/gcp_cups_connector/gcp-cups-connector.config.json

Nov 16 11:06:16 gray-server systemd[1]: Started Google Cloud Print CUPS Connector.
Nov 16 11:06:16 gray-server gcp-cups-connector[1549]: E1116 11:06:16.808102    1549 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version 2015.10.05-linux
Nov 16 11:06:16 gray-server gcp-cups-connector[1549]: Google Cloud Print CUPS Connector version 2015.10.05-linux
Nov 16 11:06:18 gray-server gcp-cups-connector[1549]: E1116 11:06:18.133121    1549 gcp-cups-connector.go:141] Ready to rock as proxy 'HP_PRINTER' and in local mode
Nov 16 11:06:18 gray-server gcp-cups-connector[1549]: Ready to rock as proxy 'HP_PRINTER' and in local mode
```

**Comment by jacobmarble** [comment]
@hubertbanas can you comment here? He wrote the wiki page.

**Comment by jacobmarble** [comment]
@JasonLG1979 what does the log say after reboot? Should be only a few lines if it fails quickly.

**Comment by jacobmarble** [comment]
To be clear, what does the connector log say?

**Comment by JasonLG1979** [comment]
/tmp/connector.INFO is not created. My guess is because the connector never starts.

**Comment by JasonLG1979** [comment]
Yep. replacing:
```After=printer.target```
With:
```After=printer.target network.target multi-user.target```

Did the trick.

**Comment by jacobmarble** [comment]
Good to know.

I haven't taken the time to learn systemd yet; would you mind updating the wiki?

**Comment by JasonLG1979** [comment]
> would you mind updating the wiki?

Just did ;)

**Comment by jacobmarble** [comment]
Thanks for doing that.

**Comment by JasonLG1979** [comment]
I'll update the wiki further with step by step instructions later as far as making the dirs and moving the files around and setting proper file permissions and such.

**Comment by peterlewis** [comment]
Still failing on Raspbian 2, even after setting. Could it be that it needs to come even later in startup?:
    After=printer.target network.target multi-user.target

**Comment by fmanco** [comment]
Hi

Just had a similar issue. For me the following works:

```
[Unit]
Description=Google Cloud Print CUPS Connector
Wants=network-online.target time-sync.target
After=network.target network-online.target time-sync.target
```

On my system the problem was not being online yet at the time the service was being started, and therefore the need for `network-online.target`.

**Comment by ajorg** [comment]
I still had problems even with `network-online.target` on Arch Linux. Adding `Restart=on-failure` to the `[Service]` section seems to have done it.

It's worth considering if it's better to have it bail out on failure to connect (and require the system to retry it) or better to have the connector do the retries. Given that the service is useful on the local broadcast domain even when it cannot connect, I'd rather have the connector do the retries.

It would also be bad if the connector bailed out when losing a connection. Not sure if it does that.

**Comment by asprunt** [comment]
Having the same problem (connector fails to start on boot, but will start from command line). I have the `network-online.target` modification. The `Restart=on-failure` modification did not work for me, so I've removed it.

I do get an error message in `/tmp/gcp-cups-connector.FATAL`:

>Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1229 23:15:23.882132     490 gcp-cups-connector.go:89] While starting XMPP, failed to get access token (password): Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com on [::1]:53: read udp [::1]:33719->[::1]:53: read: connection refused
goroutine 1 [running]:

**Comment by jacobmarble** [comment]
I know nothing of systemd, but that error looks like a DNS lookup failure. If the NIC isn't up at the time the connector runs, then this is the error you should see.

**Comment by ajorg** [comment]
The network-online target in systemd is supposed to be reached only when the network is up and a path to the Internet exists. So the NIC should definitely be up at the time the connector runs. But systemd cannot guarantee that the connection is stable. That's part of why I'm suggesting that the connector should not bail out whenever the network isn't ideal.

**Comment by jacobmarble** [comment]
I understand. If you would like to point to a common service that handles an unstable connection state better, then I would consider adopting that service's strategy. It's clearly A Good Idea.

We do handle stable=>unstable after start by retrying the connection repeatedly. This was a big problem early on.

The connector (configured for cloud) truly depends on a functioning Internet connection. All incoming print jobs come from the Cloud Print service, so without a functioning Internet connection, there's no reason for the connector to live.

**Comment by ajorg** [comment]
The local mode doesn't depend on Internet, does it?

**Comment by jacobmarble** [comment]
That is correct. However, if both local and cloud are enabled, then the connector will fail to start without a functioning Internet connection.

Yes, this could be improved.

So what is your proposed strategy? Here are a couple:
- Retry for n seconds before giving up: Kind of hacky.
- Retry for ever, while local mode functions fine: What if the network never arrives?

**Comment by ajorg** [comment]
It's easy to be persuaded that if local mode is enabled, a broken cloud mode should not cause the connector to exit.

If network never arrives the printer will remain offline so there's some indication to the operator that things are not all well. End users also have the same indicator, but at least if they are on the same network (as they will tend to be because they'll want to pick up their print job) they have some recourse to get their printing done.

You mentioned that after startup it will retry when the connection is dropped. Does it do that indefinitely? Are there reasons why we'd want to differentiate between startup and later connection problems?

I think retrying forever makes sense as long as that doesn't mean logs are going to get clobbered quickly.

**Comment by jacobmarble** [comment]
Please open a new issue for this so that we can discuss it there. Your logic makes sense.

**Comment by ajorg** [comment]
Sure, I can do that, and I can see how it can be viewed as not the same issue as this.

**Comment by mirceanis** [comment]
Hello all, 
I found a workaround until #160 gets fixed.

I experienced the same difficulties with failed auth because of no-network on RaspberryPI 2 with Raspbian Jessie and managed to work around it by setting 
```
Restart=always
RestartSec=10
```
in the `gcm.service` file
The 10 second delay between restarts probably can be fiddled with but it worked for me.

Cheers!

**Comment by cheld** [comment]
Hi all,

the last worked around works for me, too. Thanks

Cheers

**Comment by tryandbuy** [comment]
I can not even do:
systemctl status gcp

I receive the following error:
Failed to get D-Bus connection: Unknown error -1

Thanks for help

**Comment by Joehc** [comment]
Me too - any news on this?

**Comment by agoode** [comment]
@Joehc @tryandbuy are you still getting the dbus errors? This is likely not a cloud print issue.

**Comment by agoode** [comment]
Take another look at https://github.com/google/cups-connector/wiki/Run-Connector-Automatically-on-Boot. I updated the service file there to try to be more robust.

Specifically, these lines:
```
[Unit]
After=printer.target network-online.target
Wants=network-online.target
```
and
```
[Service]
Restart=on-failure
```

**Comment by agoode** [comment]
So until #160 is fixed, I think the systemd file in the wiki provides the most robust workarounds available.

**Comment by agoode** [comment]
I tweaked the systemd file on the wiki again. Disregard the lines in my comment above, they are out of date.

**Comment by kylemacfarlane** [comment]
Using the latest service file on my Raspberry Pi it still wouldn't start properly on boot. Looking in journalctl it said that the cloud-print-connector was trying to restart too fast and stopped trying to start it.

Adding `RestartSec=10` seems to have fixed it for me.

**Comment by agoode** [comment]
Take a look at #355 which should provide the correct systemd config to restart indefinitely. Sorry I did not catch this before.

**Comment by ding-bang-ow** [comment]
adding
Environment=CUPS_ENCRYPTION="NEVER connector"
before the ExecStart worked for me

**Comment by madanbisht** [comment]
Apr 23 01:05:32 iwf1115175 systemd[1]: omni@4632-127.0.0.1:5590-127.0.0.1:46388.service: Unit entered failed state.
Apr 23 01:05:32 iwf1115175 systemd[1]: omni@4632-127.0.0.1:5590-127.0.0.1:46388.service: Failed with result 'exit-code'.


Thanks it gets resolved  with:
Restart=on-failure
