### ISSUE TITLE
Add CUPS options as GCP vendor capabilities

### ISSUE THREAD

**Issue by akorobkin** [google/cloud-print-connector#195]
Looks like January 2016 release filters out too many important options from the print dialog UI:
Paper type, Thickness, Staple, Punch, Color Profile are all missing for Ricoh printers. 

Ideally nothing should be filtered, or an option provided to have basic vs advanced dialog.

**Comment by atlemagnussen** [comment]
Cups-connector does not have a UI?

**Comment by jacobmarble** [comment]
I think @akorobkin means that the dialog belonging to Cloud Print clients, like Chrome.

**Comment by jacobmarble** [comment]
@akorobkin I removed the extra stuff on purpose. There was too much useless stuff coming from certain drivers, so that the advanced dialog was difficult to manage. The New Way is to explicitly add whatever features we want to enable, so that they can be properly vetted. For example, you'll notice that the Ricoh print job password is much better than it used to be.

Please identify, explicitly, which options you need added, and then I'll add this to the 1.0 milestone.

**Comment by akorobkin** [comment]
OK, these ones please (based on Ricoh C3502, C3003, C5503, C305 model drivers)

MediaType/Paper Type: 
InputSlot/Media Source:
Rimagesm/Image Smoothing:
RPSBitsPerPixel/Gradation: 
RPSRGBcorrect/Color Setting:
RPSColorRendDict/Color Profile: 
RPSColorUniversalDesign/Barrier-free Color Management: 
RPSDitherType/Dithering:
RPSBlackMode/Gray Reproduction (Text/Line Art): 
Rcmyksimulation/CMYK Simulation Profile: 
OutputBin/Destination: 
StapleLocation/Staple: 
RIPunch/Punch:
RIFoldType/Fold Type:
OverlapFold/Multi-sheet Fold:
RIRotateBy180/Rotate by 180 degrees: 
RIOrientOvr/Orientation Override: 
Booklet/Booklet:

HP DesignJet options (based on T1300, z5200, T1100 drivers):

HPOutputQuality/Print Quality: 
HPMaxDetail/Maximum Detail:
HPColorOutput/Color Mode:
HPPantone/HP Professional PANTONE Emulation:
HPMarginsUsing/Margin/Borderless:
HPSaveRollPaper/Remove Top/Bottom Blank Areas:
HPAutoScaling/Print Document on: 
HPCropMarkPrinting/Crop Lines:
HPTransverse/Rotate by 90 Degrees:
HPAutorotate/Auto rotate:
HPMirrorOutput/Mirror Image: 
HPDisableAutoCutter/Disable Automatic Cutter: 
HPMarginsLayoutMode/Print With Margins:
HPImageEnlargement/Image Enlargement: 
HPIQSlider/Slider:
OutputMode/Quality:
HPMorePasses/More Passes:
HPPaperSource/Paper Source:
HPApplyMidtoneToAll/Apply Midtone Adjustment to All: 
InputSlot/Mediasource:

**Comment by dschuuls** [comment]
+1 from me. can't use my dymo labelwriter 450 with cups-connector on raspberry pi. all the needed settings are missing! works when i connect the printer to my ubuntu machine and share via chrome.

![pi-cups-connector_preview](https://cloud.githubusercontent.com/assets/18231300/14226699/02dd59d8-f8ea-11e5-9c49-dcc2112448fc.png)
![pi-cups-connector_settings](https://cloud.githubusercontent.com/assets/18231300/14226702/02de1a08-f8ea-11e5-9041-ddd694081dab.png)

![ubuntu-chrome_preview](https://cloud.githubusercontent.com/assets/18231300/14226701/02ddaec4-f8ea-11e5-9329-87ee652a7408.png)
![ubuntu-chrome_settings](https://cloud.githubusercontent.com/assets/18231300/14226700/02dd7fd0-f8ea-11e5-9fa5-3a2d2c54d692.png)

**Comment by jacobmarble** [comment]
@dschuuls Please identify, explicitly, which options you need added.

**Comment by agoode** [comment]
I understand this approach of having whitelist-only options, but am concerned about the human scalability of it.

What were the UI issues? Is there a link to an issue I can look at? Is it possible to fix this on the Chromium side?

Would you be opposed to exposing this as an administrator-controlled configuration option? Are code changes really needed for each option?

**Comment by kaned-mchs** [comment]
I have:

Xerox D110
Xerox 5749
Xerox 5945

and have found these in the PPD which should reference what we would need.

XRPunchOption
XRPunch
XRStapleOption
StapleLocation
Duplex


Is there a "options search string" that can be configured in the config file?  I have read up and down and am trying to figure out how to add these options but some of this is above my head.
