### ISSUE TITLE
Avahi not found when ran via systemd

### ISSUE THREAD

**Issue by jfjm** [google/cloud-print-connector#232]
Everything seems to run fine when I start the cups-connector via a user shell. However, when I execute this via systemd, it refuses to find avahi.

Here is my gcp.service file:
[Unit]
Description=Google Cloud Print CUPS Connector
After=avahi-daemon.service printer.target network.target multi-user.target

[Service]
ExecStart=/opt/cups-connector/gcp-cups-connector -config-filename /etc/gcp_cups_connector/gcp-cups-connector.config.json
Restart=on-abort
User=gcp
Group=gcp

[Install]
WantedBy=multi-user.target

Here is the log file:
I [31/May/2016:11:31:33 -0700] Google Cloud Print CUPS Connector version 2016.01.02-linux
I [31/May/2016:11:31:33 -0700] connected to CUPS server /var/run/cups/cups.sock:631 encrypting REQUIRED
W [31/May/2016:11:31:58 -0700] Cannot find Avahi daemon. Is it running?
I [31/May/2016:11:31:58 -0700] Local printing disabled (Avahi client is not running).
I [31/May/2016:11:31:58 -0700] Synchronizing printers, stand by
I [31/May/2016:11:31:58 -0700] Finished synchronizing 1 printers

However, when I execute this when logged in as gcp or root, it finds the Avahi daemon perfectly:
I [31/May/2016:11:23:50 -0700] Google Cloud Print CUPS Connector version 2016.01.02-linux
I [31/May/2016:11:23:50 -0700] connected to CUPS server /var/run/cups/cups.sock:631 encrypting REQUIRED
I [31/May/2016:11:23:50 -0700] Local printing enabled (Avahi client is running).
I [31/May/2016:11:23:50 -0700] Synchronizing printers, stand by
I [31/May/2016:11:23:50 -0700] Finished synchronizing 1 printers

Also, execute it via rc.local works fine as well.

**Comment by agoode** [comment]
@jfjm what distribution are you attempting this on?

**Comment by agoode** [comment]
Try this updated systemd file:
https://github.com/google/cups-connector/wiki/Run-Connector-Automatically-on-Boot

I just updated the wiki page to explicitly wait for cups and avahi.

If this works for you, please close the issue.

**Comment by agoode** [comment]
I just had this problem, and it was because I had incorrect selinux labels on the binary.

You might try `restorecon -Rv /opt/cups-connector` and see if that fixes anything.

**Comment by jfjm** [comment]
Thank you! That solved the problem.

My distribution is CentOS 7.
