### ISSUE TITLE
Rename GitHub repository and Google Group

### ISSUE THREAD

**Issue by jacobmarble** [google/cloud-print-connector#241]
Since the Windows port release, the project is now the "Google Cloud Print Connector" so the GitHub repository should be renamed from "cups-connector" to "cloud-print-connector".

**Comment by agoode** [comment]
Group: https://groups.google.com/forum/#!forum/cups-connector

**Comment by agoode** [comment]
Also need to change it in the API console.

**Comment by agoode** [comment]
repo and group are renamed!
https://github.com/google/cloud-print-connector
https://groups.google.com/forum/#!forum/cloud-print-connector

**Comment by jay0lee** [comment]
README.md needs link to correct group (groups unfortunately do not autoforward after rename).

**Comment by agoode** [comment]
Remaining things to rename:

* https://travis-ci.org/google/cups-connector
* http://jenkins.mouf.net/job/cups-connector
* All imports (less critical since github does redirect)

**Comment by agoode** [comment]
Travis automatically updates.

**Comment by agoode** [comment]
The API project is updated.

**Comment by jay0lee** [comment]
See attached, project still showing as "CUPS Connector".

I believe we need to change the name under the "Credentials" portion of the project...

![unnamed](https://cloud.githubusercontent.com/assets/4623536/19044815/db007282-8963-11e6-97fd-f6e1ecbda4f7.png)

**Comment by agoode** [comment]
Oops, try it again. I updated the correct page this time.

**Comment by jay0lee** [comment]
Looks good now, thanks for quick action.
