### ISSUE TITLE
Add util flags: gcp-oauth-client-id, gcp-oauth-client-secret

### ISSUE THREAD

**Issue by sicklittlemonkey** [google/cloud-print-connector#248]
Each GCP Connector that I manage needs to create its own robot account using our system's refresh token, so I need to use the util's handy CLI flags to pass it the options (gcp-user-refresh-token etc) required to create the config file and robot account.

The only flags missing were:
- gcp-oauth-client-id
- gcp-oauth-client-secret

I've added these and tested it, and can submit a pull request if that's OK.

Cheers,
Nick.

**Comment by agoode** [comment]
I'm happy to review a pull request.
