### ISSUE TITLE
Poppler is GPL

### ISSUE THREAD

**Issue by sicklittlemonkey** [google/cloud-print-connector#258]
First I posted in the group/mail mailing list. No response so I'm raising this as an issue.

I've been checking the licenses of all the libraries used by the cloud-print-connector (on Windows in my case).

The only red flag to me is Poppler:
https://cgit.freedesktop.org/poppler/poppler/tree/README
"... any application using poppler must also be licensed under the GPL"

Have I missed something, or is the project taking a "dynamically linked, therefore ..." or "not directly using GPL'd source code, therefore ..." perspective on this library?

Cheers,
Nick.

**Comment by agoode** [comment]
There are some additional things we need to do before distributing windows binaries, but linking to poppler doesn't change the license of this source code.

**Comment by sicklittlemonkey** [comment]
Thanks for your comment.
