### ISSUE TITLE
Firewall issue

### ISSUE THREAD

**Issue by jfjm** [google/cloud-print-connector#262]
I am creating the issue again since I can not reopen the issue that's not closed by me.

The original question/issue was:
Is there a way to specify what port to be used by cups-connector via the configuration file? I am running this on a machine that has firewall enabled, and with connector selecting a random port each time, it makes it difficult to automate startup process.

The clarify the issue, it is the listening port that I am referring to since I do allow outgoing connection by default. It is the incoming connection that I need to specify in the firewall rule.

@agoode, I tried your suggestion of gcp-connector-util init -help, and I was not able to find info on --local-port-low or high option, and I was not able to find that in the documentation on the wiki page as well. Are these ports for outgoing or listening ports? I am running version 2016.01.02.

**Comment by agoode** [comment]
Those options are not available in the old release. You can either build from git or wait for a new release.

What system are you running this on? It may be relatively easy for you to build a new release.

**Comment by jfjm** [comment]
That did the trick!

However, I did discover a new issue from the build:
gcp-connector-util init seems to be broken, instead of writing out a config file with all the options with its default values (as in the past), it only wrote the following for me (I did turn off cloud printing):
{
  "local_printing_enable": true,
  "cloud_printing_enable": false,
  "log_level": "INFO",
  "log_file_name": "/tmp/cloud-print-connector"
}
I also received this error:
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

**Comment by agoode** [comment]
The `cli` issue is #223 and shouldn't cause serious problems.

The change in the init file behavior is intentional, see #196. To get all the options, run the utility with `-backfill-config-file`.
