### ISSUE TITLE
perm session

### ISSUE THREAD

**Issue by gl82uk** [google/cloud-print-connector#268]
hi im installing this on my raspberry pi

what i want to know is once i have ran the applicaiton and its authenticated my account and obtained its tokens and I have added it as a program to startup on bootup of my pi. Will it remain active permanently?

So even if I power my pi off and turn it back on. As long as it has power and has internet access will my pi remain "online" with google as a software connector between the cloud and it printer attached to the pi?

**Comment by sicklittlemonkey** [comment]
Have you read the wiki? If you follow the RPi section it then links to:
https://github.com/google/cloud-print-connector/wiki/Run-Connector-Automatically-on-Boot

**Comment by agoode** [comment]
Yes, if everything is working correctly, it should run automatically as a service at startup.

**Comment by gl82uk** [comment]
what ive noticed is when a print job comes through to our 58mm thermal printer it prints massive and its as if its expecting to go to an a4 page size

can this be changed ? so its all within the size of the printer?

**Comment by agoode** [comment]
It's hard to tell. The cloud print connector tries to understand what the driver is describing, but sometimes it gets it wrong.

If you see a specific problem, please file a new issue with details.
