### ISSUE TITLE
Depreciated Action Signature

### ISSUE THREAD

**Issue by mathemuse** [google/cloud-print-connector#278]
>Keep it somewhere safe, as it contains an OAuth refresh token.
>DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

This seems to be causing me to not get the program working correctly.  What should I do?

**Comment by mathemuse** [comment]
Also half the wiki uses a different directory for some reason.

**Comment by agoode** [comment]
Sorry about this message, it's misleading and isn't the cause of any real problem. See #223.
