### ISSUE TITLE
"Installing on Raspberry Pi Raspbian Jessie" file directories and created user not matching with "Run Connector Automatically on Boot"

### ISSUE THREAD

**Issue by JMSarDev** [google/cloud-print-connector#287]
With the updated "Run Connector Automatically on Boot", in the "Installing on Raspberry Pi Raspbian Jessie" the following changes have to be done:

- [x] Create cloud-print-connector user instead of gcp

- [x] The directory for executables has to be /opt/cloud-print-connector/ instead of /opt/gcp_cups_connector

- [x] The gcp-cups-connector.config.json file has to be in /opt/cloud-print-connector/ instead of /etc/gcp_cups_connector/

- [x] Ownership commands have to be updated for the cloud-print-connector user

**Comment by agoode** [comment]
I think this is done, please check the wiki and close this issue if it looks good. Thanks!

**Comment by JMSarDev** [comment]
Nope, that is the base I was using for the pull request before. This Wiki page needs to be updated. I can update it if you wish.

**Comment by agoode** [comment]
Oh! Sorry, I totally misread. Yes, please update if you can! Thanks.

**Comment by JMSarDev** [comment]
That should be it and should be working with the new project name as well as with the service file for the autoboot.
