### ISSUE TITLE
Remove prompt for proxy name on init 

### ISSUE THREAD

**Issue by falcantara** [google/cloud-print-connector#295]
Was wondering if we could remove the prompt setting a name for the proxy when init is run.
Chrome connector auto-generates the proxy name if you look at the servicestate file.

**Comment by jay0lee** [comment]
Frank is on my team and raised this. I agree that unless there's some good reason user would need to control naming of the proxy, we should just generate a string and use it. It's confusing to admins to prompt for this without explaining what it is or does. As Frank pointed out, the Chrome connector just generates a random string for proxy id.
