### ISSUE TITLE
Windows Connector util name

### ISSUE THREAD

**Issue by sicklittlemonkey** [google/cloud-print-connector#296]
Just a quickie.

The name and usage example don't match. Is this correct, or will the util name change to include "windows" in the future?

```
C:\Program Files\Google\Cloud Print Connector>gcp-connector-util.exe
NAME:
   gcp-windows-connector-util - Cloud Print Connector for Windows utility tools

USAGE:
   gcp-connector-util.exe [global options] command [command options] [arguments...]
```

**Comment by jacobmarble** [comment]
You're right, those should agree. "gcp-connector-util" is the correct name. I'm away on vacation, but happy to accept your pull request.
