### ISSUE TITLE
Windows retain/release deletes paused jobs

### ISSUE THREAD

**Issue by sicklittlemonkey** [google/cloud-print-connector#301]
This will affect any print management software (like ours) that pauses print jobs during spooling. Maybe this only affects me for now, but I thought I'd document what I've found. I'm still searching for a work-around, but #290 is likely the most robust solution. (The connector not releasing paused jobs would be nice, but would introduce a race condition.)

The recent change to retain/release timing in #289 revealed this problem for me.

It's not documented behaviour, but when the release command is sent to the spooler with SetJob it deletes the print job - ignoring the paused flag - in which case the job is never printed. Despite that, it does a little status dance for those watching notifications. You see: deleting, printed, deleted.

**Comment by sicklittlemonkey** [comment]
A work-around for now is the following code change to the connector.

I moved the retain command into func (ws *WinSpool) Print(...) just after the printPage() for loop, and only do that if the job isn't paused. This gives time for print management software to pause the job (which happens as soon as the spooling notification is seen).

Is this worth a PR, or am I the only person who cares? ; - )

**Comment by mfly** [comment]
I guess moving ```SetJobCommand(jobID, JOB_CONTROL_RETAIN)``` after job is scheduled also creates a race-condition between gcp, spooler and third-party software and in rare occasions may lead to unexpected behavior.
What was the reason it worked before #289 ? Was the job released before it got paused from the outside world?
Paused jobs handling is still a little buggy as described in https://github.com/google/cloud-print-connector/issues/284#issuecomment-236870013.
I agree that we should move to solution suggested in https://github.com/google/cloud-print-connector/issues/290.

**Comment by sicklittlemonkey** [comment]
It's impossible to completely avoid race conditions when trying to control the spooler externally. The only way to be sure is your own driver/port (etc) components, or using DLL injection (which I've done, reluctantly). The best we can do is arrange the timing of events to minimize the risk.

The reason it worked before 289 was that release happened before EndDoc() when the job was still spooling, so at least the spooler checks for that.

290 would be quite a bit of work. I might be able to help, but PR #301 solves my problem for now with no obvious downsides.

**Comment by ejohnsonTKTNET** [comment]
> Is this worth a PR, or am I the only person who cares?

You're not the only person who cares. I'm also affected by paused jobs being deleted upon release.

**Comment by sicklittlemonkey** [comment]
@ejohnsonTKTNET Hi Eric. Could you perhaps elaborate on the problem you were experiencing and whether PR #304 helped? The PR has been rejected, so it would be good to know if there's more support for it.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
The issue of paused jobs in Windows being deleted persists, so I've resubmitted my PR #419, as suggested.

If someone cares to test it this time before rejecting, it can be easily reproduced. Line 652 in winspool.go is:
```
err = hPrinter.SetJobCommand(jobID, JOB_CONTROL_RETAIN)
```
Insert the following line before it, so the code now reads:
```
hPrinter.SetJobCommand(jobID, JOB_CONTROL_PAUSE)
err = hPrinter.SetJobCommand(jobID, JOB_CONTROL_RETAIN)
```
Any job printed by the connector will now magically disappear rather than print. This is easiest to see if you set the printer port to one which would normally error and stall the job, say LPT1.

**Comment by sicklittlemonkey** [comment]
Oh, another simple way to test it without a code change - and separate from the issue of interop with software that pauses jobs - is to just print a long document, say 100 pages, and pause the job manually as any user can (right click -> pause in the Windows print queue UI) while it's spooling. After spooling the job will be deleted rather than being printed.
