### ISSUE TITLE
Pending Red Hat Patch required to build on Fedora 24

### ISSUE THREAD

**Issue by mettacrawler** [google/cloud-print-connector#305]
This bug prevented me from building on Fedora 24. You might want to add a note to the wiki about it.
https://bugzilla.redhat.com/show_bug.cgi?id=1038683

Red Hat deprecated a function that elliptic.P224() requires claiming copyright issues (see bug report).

I had to removed the calls in ocsp.go to overcome this.

    $ diff -u ocsp.go.DIST ocsp.go
    --- ocsp.go.DIST	2016-09-11 16:21:51.533225622 -0400
    +++ ocsp.go	2016-09-11 16:22:08.940541693 -0400
    @@ -158,9 +158,6 @@
     		pubType = x509.ECDSA
 
     		switch pub.Curve {
    -		case elliptic.P224(), elliptic.P256():
    -			hashFunc = crypto.SHA256
    -			sigAlgo.Algorithm = oidSignatureECDSAWithSHA256
     		case elliptic.P384():
     			hashFunc = crypto.SHA384
     			sigAlgo.Algorithm = oidSignatureECDSAWithSHA384

Thanks

**Comment by agoode** [comment]
Wiki updated, thanks for your bug here and comment at https://bugzilla.redhat.com/show_bug.cgi?id=1038683
