### ISSUE TITLE
Connector service fails to start on Windows reboot 

### ISSUE THREAD

**Issue by falcantara** [google/cloud-print-connector#312]
Service startup type is set to Automatic but upon reboot I get the following error in the event viewer:
FATAL While starting XMPP, failed to get access token (password): Post https://accounts.google.com/o/oauth2/token: dial tcp: GetAddrInfoW: No such host is known.

Starting the service manually from services.msc works fine with no errors.

Maybe service is starting before networking is up?

Connector installed via msi on Windows Server 2012 R2

**Comment by jacobmarble** [comment]
We have heard of similar problems in Linux. You can try adding a dependent service to the Cloud Print service. Currently, the connector only depends on the Print Spooler. If this leads to a solution, then we can make the change permanent for future users by modifying the code, so please follow up on this issue.
![screen shot 2016-09-29 at 9 12 27 am](https://cloud.githubusercontent.com/assets/622263/18962402/8657fa84-8625-11e6-9af1-db4f434f3185.png)

http://stackoverflow.com/questions/3194737/wait-for-network-configuration-to-be-complete-in-windows-service-startup

http://serverfault.com/questions/24821/how-to-add-dependency-on-a-windows-service-after-the-service-is-installed

**Comment by jay0lee** [comment]
I'm working on a pull request with a number of enhancements to the Wix MSI build including a dependency on Tcpip.
