### ISSUE TITLE
MSI install fails unless it's run with elevated priveleges

### ISSUE THREAD

**Issue by jay0lee** [google/cloud-print-connector#316]
Steps to reproduce:
1. build MSI using instructions at: https://github.com/google/cloud-print-connector/tree/master/wix
2. run MSI as an admin user without elevating privileges (just click MSI file).
3. observe, install runs through, init cmd window is run and generates config.json but config.json file is NOT copied to ProgramData folder. Without config file, service fails to start.
4. run MSI as an admin user and with elevated privileges (for example open cmd.exe via "run as administrator")
5. observe,  install runs through, init cmd window is run and generates config.json, config.json file IS copied to ProgramData folder properly. Service start succeeds.

**Comment by jay0lee** [comment]
@arastooz can you take a look? I believe this issue existed before my recent changes to windows-connector.wxs. It seems to be some kind of permissions issue where ManualInit is run as the user (and thus unevelated privileges but if you grant elavated privileges at MSI run time ManualInit runs with elevated privileges. CopyFile doesn't seem to run at all if ManualInit didn't have elevated privileges.

**Comment by arastooz** [comment]
Manual init shouldn't run elevated.  It just creates the config file in TempFolder which is then copied to ProgramData during the execute sequence.  What appears to be happening is that the ServiceControl elements' Name attribute is not the same as the name of the service that should be started (or stopped).  I tested with this change, and it does work as expected.

**Comment by jay0lee** [comment]
Unfortunately that doesn't seem to solve. Service still fails to start because config file does not exist. I'll attach MSI logs from a failed user install.

**Comment by jay0lee** [comment]
MSI logs are at:

https://drive.google.com/a/u.jaylee.us/file/d/0B_jQhAK09GrKb2JmU05WMmxpcFk/view?usp=sharing

@arastooz if it'd help, I can share a GCE VM where I am experiencing the issue (it's basically just a clean GCE Windows Server 2008 VM).

**Comment by arastooz** [comment]
Can you get verbose logs?  msiexec /l*v
The lines I'm looking to see aren't there in the non-verbose logs.
I can look at the VM too.

**Comment by jay0lee** [comment]
First run was with /l*x, here it is with /l*v

https://drive.google.com/open?id=0B_jQhAK09GrKTHQtQzR2dWx3TGs

**Comment by jay0lee** [comment]
Sorry, that was `/l*x` and `/l*v` (dang markup).

**Comment by arastooz** [comment]
That machine has different temp folder paths for the unelevated and elevated contexts, which is causing the file copy to fail, because it is trying to copy from the elevated temp folder (C:\Users\jayhlee\AppData\Local\Temp\2\), but the file was created in the unelevated folder (C:\Users\jayhlee\AppData\Local\Temp\).  I'll have to figure out to get that setup on my machine and figure out how to make sure the SetProperty calls are done properly.

**Comment by jay0lee** [comment]
Yes, I believe the difference occurs when using remote desktop (RDP). RDP sessions have `%temp%` set to %TEMP%\2, %TEMP%\3, etc.

So the issue may be specific to RDP, can we pass the full path between unelavated and elevated so RDP Is supported?

**Comment by arastooz** [comment]
I think it may be as simple as changing the SetProperty element that sets ConfigFile to have Sequence="first" instead of "both"  I'll have to get a moment to try that out.
