### ISSUE TITLE
Can't install from apt

### ISSUE THREAD

**Issue by abalnflx** [google/cloud-print-connector#331]
Installing this on a new server running 14.04, with I think are the default repos:

abalingit@gcp$ sudo apt-get install google-cloud-print-connector
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package google-cloud-print-connector

Which repo should I add?

Thanks!

**Comment by jacobmarble** [comment]
The Debian package is the unstable/testing repos, and I haven't updated it in a long time.
