### ISSUE TITLE
cloud-print-connector.service  Active: inactive (dead)

### ISSUE THREAD

**Issue by alexsgger** [google/cloud-print-connector#350]
I followed the instructions for Rasbian (Jessie). After boot the service is inactive:

root@10102:~# sudo systemctl status cloud-print-connector.service -l                                                    
● cloud-print-connector.service - Google Cloud Print Connector
   Loaded: loaded (/etc/systemd/system/cloud-print-connector.service; enabled)
   Active: inactive (dead) since Mon 2017-03-20 22:42:20 CET; 31s ago
     Docs: https://github.com/google/cloud-print-connector
  Process: 530 ExecStart=/opt/cloud-print-connector/gcp-cups-connector -config-filename /opt/cloud-print-connector/gcp-cups-connector.config.json (code=exited,                                         status=0/SUCCESS)
 Main PID: 530 (code=exited, status=0/SUCCESS)
Mar 20 22:42:20 10102.cps.domain.com systemd[1]: Started Google Cloud Print Connector.
Mar 20 22:42:20 10102.cps.domain.com gcp-cups-connector[530]: Google Cloud Print Connector for CUPS version DEV-linux

After
sudo systemctl start cloud-print-connector.service:
● cloud-print-connector.service - Google Cloud Print Connector
   Loaded: loaded (/etc/systemd/system/cloud-print-connector.service; enabled)
   Active: active (running) since Mon 2017-03-20 22:54:33 CET; 6s ago
     Docs: https://github.com/google/cloud-print-connector
 Main PID: 1216 (gcp-cups-connec)
   CGroup: /system.slice/cloud-print-connector.service
           └─1216 /opt/cloud-print-connector/gcp-cups-connector -config-filename /opt/cloud-print-connector/gcp-cups-connector.config.json

Mar 20 22:54:33 10102.cps.domain.com systemd[1]: Started Google Cloud Print Connector.
Mar 20 22:54:33 10102.cps.domain.com gcp-cups-connector[1216]: Google Cloud Print Connector for CUPS version DEV-linux
Mar 20 22:54:36 10102.cps.domain.com systemd[1]: Started Google Cloud Print Connector.
Mar 20 22:54:37 10102.cps.domain.com gcp-cups-connector[1216]: Ready to rock as proxy 'eb9db293-b337-4d09-9d40-3ab3b4898022' and in local mode

Has anybody an idea?

**Comment by aglozier** [comment]
I have the same issue.  From what I read here [Why is my Systemd unit loaded, but inactive (dead)?](http://unix.stackexchange.com/questions/137028/why-is-my-systemd-unit-loaded-but-inactive-dead), it appears that the cloud print service is loading and then exiting.

Any help would be appreciated.

**Comment by agoode** [comment]
By default, systemd will give up trying to restart a failed service after a while. This is surprising to me, but it is documented to do this. See https://github.com/systemd/systemd/issues/2416.

I suggest editing the systemd config so that it will indefinitely try to restart cups-connector.

**Comment by aglozier** [comment]
I got it to work using this:

`Restart=always
RestartSec=90
StartLimitInterval=400
StartLimitBurst=3`

It originally had:

`Restart=on-failure`

Since the service would first start and them exit successfuly (no failure) it would never try to restart.

Thanks agode for pointing me in the right direction.
