### ISSUE TITLE
Version 1.13 and 1.12 point to the same commit

### ISSUE THREAD

**Issue by MauroMombelli** [google/cloud-print-connector#383]
Seeems version 1.12 commit/tag is wrong, as it require go 1.9.x to compile

**Comment by pastarmovj** [comment]
Yeah there is something weird with these two releases. Especially since I indeed authored the change that is mentioned in 1.12 but have not done a release myself, nor committed something new.

@jay0lee : Do you know why this has happened?

**Comment by jay0lee** [comment]
Yes, there's no changes to the connector source between these releases. The changes were to the msys2 Windows build environment (cairo dll in particular) and the Golang compiler which are local to the build system.

**Comment by MauroMombelli** [comment]
please note 1.12 say to be 1.8 compatible, but it give me a compilator error.
