### ISSUE TITLE
How to install google cloud print connector without starting the service

### ISSUE THREAD

**Issue by ChrisMagnuson** [google/cloud-print-connector#386]
I have created an automated choclatey package for [Google cloud print connector](https://github.com/Tervis-Tumbler/au-packages/tree/master/google-cloud-print-connector) but for it to be an official chocolatey package it has to be able to install silently without specifying any parameters.

I have been able to do a silent install by specifying `INITPARAMS="--gcp-user-refresh-token=<SomeToken> --share-scope=<SomeEmail>"` but none of the following work:

- Don't specify anything
- - Shows the MSI command line options help gui
- `INITPARAMS=""`
- - Hangs on starting service
- `INITPARAMS="--gcp-user-refresh-token= --share-scope="` 
- - Hangs on starting service
- `INITPARAMS="--gcp-user-refresh-token=1234 --share-scope="`
- - Hangs on starting service

Is there anyway to install this without starting the service or something else that will all me to publish this package and then allow people to either specify package parameters for those values or write out the .json configuration file themselves after the install completes?

**Comment by jay0lee** [comment]
See:

https://github.com/google/cloud-print-connector/wiki/Windows-MSI-Parameters

for silent install options.
