### ISSUE TITLE
Cannot start service "Cloud Print Connector"

### ISSUE THREAD

**Issue by jeffreyoelen** [google/cloud-print-connector#406]
Hi All, 

Since a few days I do have an problem with starting the "Cloud Print Connector" service. I am running it on a windows machine, and running version 1.15. 

The message that i receive during the installation is: 
Service 'cloud print connector' failed to start. Verify that you have sufficient privileges to start system services. (I am using an local admin account so this should be okay)

Do you maybe know what could be the problem here? Things i can do to troubleshoot? 

Kind regards, 
Jeffrey Oelen

**Comment by jay0lee** [comment]
Try opening the service in services.msc and copying the exact command the
service start runs. Then, with the service stopped, open a command prompt
and run that command. This should give you some idea why the service isn't
starting.

Jay

**Comment by jeffreyoelen** [comment]
Hi Jay, 

I think this is not possible right now, this because we did uninstall the connector, and installing an new version right now. The installation is stuck at starting the service right now. I only can click retry (dont help) or Cancel which stopping the installation.

**Comment by jay0lee** [comment]
If you don't make the right choices in the command prompt when installing then the service will fail to start and you'll just need to cancel the installation and start it over again. You might try using the options at:

https://github.com/google/cloud-print-connector/wiki/Windows-MSI-Installation

**Comment by whiff2** [comment]
By chance did you change the password of the local admin account that you use for the service permissions?

**Comment by borderst** [comment]
I experienced this problem when I had exceeded the 100 printer limit on the server that I was installing the connector on. Cloud printers are limited to 100 per account as I understand it. Working solutions were to prune unused printer objects or to use the config file to exclude printers that wouldn't be shared. Really hoping this helps someone out as this had me scratching my head for a bit.
