### ISSUE TITLE
cups_vendor_ppd_options not working

### ISSUE THREAD

**Issue by kaned-mchs** [google/cloud-print-connector#422]
We recently upgraded versions to the latest version in the apt repo on Ubuntu 16.04.

We have run through the configuration and have everything working except the vendor options.

Reading the documentation it appears that we can simply place:
`  "cups_vendor_ppd_options": [
    "all"
  ],`
in the root of the conf.  Doing so has resulted in no changes to teh options provided.  I have also identified multiple options in our PPD file to explicitly allow:
`  "cups_vendor_ppd_options": [
    "all"
  ],`
Also with no effect.

Due to lack of formatting in the code option, I used a pastebin link to show my config with soem redacted information:  

Use with all vendor options: [https://pastebin.com/gxJrKzYV](urk)
Use with specific vendor options:  [https://pastebin.com/BQ0tiewQ](url)

I did restart the daemon and wait several minutes for changes to take effect with no avail.

I know this feature worked in a previous release as we used this for several years.

We are a school who need the basic hole punch and staple options to work (duplex already works).  

I would welcome any suggestions as school starts in about 2 weeks and I would like to avoid any major disruptions.

Thanks!

**Comment by kaned-mchs** [comment]
@agoode, any thoughts?

**Comment by kaned-mchs** [comment]
I apparently did not catch that I didn't list the PPD options.  I can get those later.

those would be XRStapleOption and XRPunchOption.

I will work on compiling from source today.

**Comment by agoode** [comment]
Did the options in the PPD change? Can you link to the PPD that CUPS is using?

**Comment by kaned-mchs** [comment]
No, we were running a version 2-3 years old.  We ran into issues with XMPP connecting and decided that we needed to update the software (as a troubleshooting step).

This allowed us to connect properly without XMPP issues however now the vendor_options are now a problem.

This is a problem for all of our multifunction copiers (which happen to all be Xerox).  Those are a manually defined PPD file within cups (which has not changed).

There are 2 models/PPD's effected.  

See this PPD file:  [https://pastebin.com/Kb1bqz2j](url)

I would be happy with the "all" option, but the two biggest issues are XRStapleOption and XRPunchOption.

**Comment by agoode** [comment]
The version in ubuntu 16.04 is quite old and predates the vendor PPD option support:
https://packages.ubuntu.com/xenial/google-cloud-print-connector

You will need to build from source to have this functionality.

**Comment by kaned-mchs** [comment]
If I dist-upgrade to Bionic, would that version suffice?

I have had problems getting Go working on 16.04 previously.

I'm going to take another snapshot and get this going.  Need to upgrade anyway...

**Comment by kaned-mchs** [comment]
meant to include this:  [https://packages.ubuntu.com/bionic/google-cloud-print-connector](url)

**Comment by agoode** [comment]
Yes, version 1.12 in bionic seems recent enough.

I'm going to close this issue but please reopen it if you still have problems with the new version.
