### ISSUE TITLE
Networked Printer

### ISSUE THREAD

**Issue by FA-Grosshans** [google/cloud-print-connector#437]
We have a desktop printer that is shared on our local network. I would like to have the connector installed on our Print server VM even though the printer is physically connected to another PC. I can add the printer to my cloud print account via chrome://devices and it will show up... until I log out of the remote session and it simply disappears completely from our GCP list. It does not show as offline it just disappears completely. When installing via the MSI it didn't grab that printer from the server even though it was installed and set as the default printer.

**Comment by brechtvhb** [comment]
I am havign the same problem.

I've treid playing with the settings in the configuration file but the printer remails invisible for the Cloud print connector.

**Comment by jay0lee** [comment]
- Don't use Chrome or chrome://devices. Chrome has it's own connector embedded that is completely separate from this one. You should be able to completely uninstall Chrome from the device and use this one.
- When running as a service, the connector will not have access to network printers only added for your Windows user. To avoid this issue, make sure you are adding all network printers as local printers:

https://superuser.com/questions/278575/how-do-i-install-a-network-printer-for-all-users-on-a-windows-7-computer
