### ISSUE TITLE
Landscape prints in portrait with clipped contents

### ISSUE THREAD

**Issue by aselaleelaratne** [google/cloud-print-connector#440]
Environment: macOS Jojave 10.14.3
CUPS: 2.2.9
Source: master @ 9386e53c4196910e4647a341c19ed7a4c7bdad9c (HEAD as at Jul 21, 2018)
Test PDF: [Test_landscape_pages.pdf](https://github.com/google/cloud-print-connector/files/2858800/Test_landscape_pages.pdf)

Problem:
When a landscape oriented document is printed using the Google cloud print web interface, the output is printed on a portrait oriented page with contents partially clipped. (As shown below)
![image](https://user-images.githubusercontent.com/47585298/52687158-c9e6d100-2fa4-11e9-8083-658aeeacd1d8.png)

Steps to reproduce:
1. Checkout revision and build on macOS
2. Install a PostScript supported printer on macOS using the Mac Generic PostScript driver
3. Execute gcp-connector-util and connect to Google account
4. Execute gcp-cups-connector to publish the printers
5. On Google Cloud Print web interface click on Print->Upload document. Upload the attached PDF, select the printer.
6. Select orientation "Landscape" or "Auto" (both give the same output)
7. Print

The printed output from printer, is as shown in the above diagram. Paused the printer queue on macOS, then grabbed the spooled PostScript file. Converted the PS file to a PDF. The output looked as same as the "Printed Output" in the diagram.

Expected output:
The printed output to look as same as the source document.

This might be a Google Cloud Print + CUPS issue as well. The outcome was same when I used "Chrome" to publish the printers and print.
Couldn't find a Google Cloud Print issue tracker.

More details here:
https://docs.google.com/document/d/1mW2zNXOUh_NrzSAQVPdbHzjt-5lEeHyFqGxucLmNyPI/edit?usp=sharing

**Comment by rnhurt** [comment]
I'm having this exact same problem with an iMac "server" running macOS 10.12.  We have several different printers (Brother & HP), ~300 Chromebook clients and ~100 iOS clients.  It doesn't matter what combination of printers + clients we use, they all truncate landscape printing the same way.  This same combination in AirPrint mode works perfectly, in both landscape and portrait mode, so I think the systems are configured correctly.

**Comment by natureofwork** [comment]
Having the same issue with Google Cloud Print + Zapier connection. Even if I specify the orientation in the ZAP it ignores and prints sideways like you've illustrated. It also seems to think it's A4 size, when it's actually just Letter sideways.

**Comment by aselaleelaratne** [comment]
This was a issue with macOS. I did raise an issue with macOS as well at the time. They got back saying it's fixed in the latest and I confirmed that it's fixed in the latest macOS release.  They have fixed in the latest version of macOS (Catalina).
